Repository NextDom/nextdom-core, pull requests merged in 2019-10, with the labels that each got.

#1388 Log Cron_execution rempli à outrance #1385
  src/Model/Entity/Cmd.php
Labels: BUG

#1407 Erreurs qui s'affichent pendant une restauration #1298
  src/Helpers/NextDomHelper.php
  src/Helpers/SystemHelper.php
Labels: BUG

#1405 Service apache non reconfiguré lors du postinst #1380
  install/postinst
Labels: CRITICAL

#1404 Mysql postinst #1374
  install/postinst
Labels: CRITICAL

#1448 Restauration via Samba #1266
  src/Repo/RepoSamba.php
Labels: CRITICAL

#1438 Vocabulary
  scripts/gen_composer_npm.sh
  scripts/gen_global.sh
  translations/en_US.yml
  translations/fr_FR.yml
  views/desktop/admin/api.html.twig
  views/desktop/admin/cache.html.twig
  views/desktop/admin/network.html.twig
  views/desktop/params/general.html.twig
Labels: FEATURE
